FROM node:16

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install global dependencies
RUN npm install -g nodemon ts-node typescript

# Copy the rest of the application code
COPY . .

# Ensure all dependencies are installed, including devDependencies
RUN npm install

EXPOSE 5000

CMD ["npm", "run", "dev"]