name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd backend && npm ci
        cd ../frontend && npm ci

    - name: Run backend tests
      run: cd backend && npm test

    - name: Run frontend tests
      run: cd frontend && npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.prod.yml build
        docker tag interactive-storytelling-frontend:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/interactive-storytelling-frontend:${{ github.sha }}
        docker tag interactive-storytelling-backend:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/interactive-storytelling-backend:${{ github.sha }}
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/interactive-storytelling-frontend:${{ github.sha }}
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/interactive-storytelling-backend:${{ github.sha }}

    - name: Deploy to GCP
      run: |
        gcloud run deploy interactive-storytelling-frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/interactive-storytelling-frontend:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

        gcloud run deploy interactive-storytelling-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/interactive-storytelling-backend:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

        gcloud run services update-traffic interactive-storytelling-frontend --to-latest
        gcloud run services update-traffic interactive-storytelling-backend --to-latest
